### ISSUE TITLE
关于basic_EA

### ISSUE THREAD

**Issue by igo312** [MorvanZhou/Evolutionary-Algorithm#1]
为什么要用正态分布去改变DNA
如何保证在DNA逐渐优化的过程中，变异强度会逐渐减弱。也是依靠计算机随机的选择么？

**Comment by MorvanZhou** [comment]
用正态分布是为了处理连续值，变异强度在是可以自适应的，比如在(1+1)ES里面，越快收敛时变异强度越小

**Comment by igo312** [comment]
是不是可以理解为，用正态分布的优化也只是一个猜测，我可以选择其他的数据相乘。只是正态分布去运算结果更为合理，或者说现有的随机数样本的限制而只使用了正态分布？谢谢回答。

**Comment by MorvanZhou** [comment]
正态分布是自然界中最常见的分布类型，所以选他比较合理。而且你会见到大部分的应用中，都存在正态分布

**Comment by igo312** [comment]
好的，谢谢。
