### ISSUE TITLE
这里有问题吧，parent 并没有真的被replace吧，用的还是pop里的。

### ISSUE THREAD

**Issue by zle1992** [MorvanZhou/Evolutionary-Algorithm#16]
https://github.com/MorvanZhou/Evolutionary-Algorithm/blob/4820978bf3bc9df6da9525159204b63ccdfc72b8/tutorial-contents/Genetic%20Algorithm/Genetic%20Algorithm%20Basic.py#L70

**Comment by wadefall** [comment]
没有问题，对parent赋值，pop的值也会发生变化。比如pop = [[1, 2], [3, 4], [5, 6]]，让pop[0] = [7, 8]，则pop就变成[[7, 8], [3, 4], [5, 6]]了。

**Comment by MorvanZhou** [comment]
谢谢回复
