### ISSUE TITLE
配置什么的写清楚呀凡哥

### ISSUE THREAD

**Issue by john826** [MorvanZhou/Evolutionary-Algorithm#21]

**Comment by MorvanZhou** [comment]
请问这个问题、建议具体是什么

**Comment by john826** [comment]
凡哥，打扰了，没有太大问题，只是运行的时候少了graphviz这个配置，需要安装配置一下，解决了，凡哥这种基于进化算法的强化学习的方法能够完虐那种传统人工神经网络的强化学习吗，有没有相关的最新论文：
建议文档写上：对应库的版本号

**Comment by john826** [comment]
哈哈哈，等你更新这种基于进化算法的强化学习，我去打赏，O(∩_∩)O哈哈~

**Comment by MorvanZhou** [comment]
恩，我在后面的教学库房了requirements.txt, 之前做的库没写。进化算法和强化学习还是有点差别的。这个教程就是用进化算法学习策略。https://mofanpy.com/tutorials/machine-learning/evolutionary-algorithm/evolution-strategy-reinforcement-learning/
