### ISSUE TITLE
Memory Error

### ISSUE THREAD

**Issue by Sat0ri** [MorvanZhou/Evolutionary-Algorithm#6]
After long using of [Evolution Strategy with Neural Nets.py](https://github.com/MorvanZhou/Evolutionary-Algorithm/blob/master/tutorial-contents/Using%20Neural%20Nets/Evolution%20Strategy%20with%20Neural%20Nets.py) have MemoryError in Multiprocessing.
Memory filled up each step, posible to clean up it?

**Comment by MorvanZhou** [comment]
Hi, are you using Windows? I have it tested on Mac and Linux, it turns out fine on these two systems. The multiprocessing on Windows is different from it on Mac and Linux. You may need to tune it for Windows.

**Comment by Sat0ri** [comment]
I use Linus, and Windows for tests but problem was in my Env, thank you.
